Publication utils
nf-osi/nfportalutils pull request #48
Opened 2022-06-28 17:03 UTC by anngvu

2022-06-28 17:33 UTC, anngvu commented
The reason check fails is still because of 
```
❯ checking package dependencies ... WARNING
  Requires (indirectly) orphaned package: ‘gtools’ 
```

2022-06-29 05:41 UTC, allaway requested changes
Hey, so this worked on your test file but because the PMIDs had already been added to the table, it exited early (e.g. "PMID:... already exists in destination table"). 

I tried this with a PMID that is not in the table, and it worked on the dry_run=T, but when I tried to actually upload the results (dry_run=F), it errored out: 

```
> new_pubs <- add_publications_from_file("~/Downloads/Publications-NFOSI-202 - Sheet1.csv", "syn16857542", "syn16787123", dry_run = T) 
Rows: 123 Columns: 1                                                                                                                                                             
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): pmid

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

> new_pubs
<synapseclient.table.CsvFileTable>

> new_pubs$asDataFrame()
                          doi             diseaseFocus                                                     journal
1 https://www.doi.org/baac045 Neurofibromatosis type 1 Database : The Journal of Biological Databases and Curation
                                                                                            title year     pmid
1 Centralizing neurofibromatosis experimental tool knowledge with the NF Research Tools Database. 2022 35735230
                                                                                                                                                                                                                                                                                                 author
1 ["Ashley Clayton","Mialy DeFelice","Brynn Zalmanek","Jay Hodgson","Caroline Morin","Stockard Simon","Julie A Bletz","James A Eddy","Milen Nikolov","Jineta Banerjee","Kalyan Vinnakota","Marco Marasca","Kevin J Boske","Bruce Hoff","Ljubomir Bradic","YooRi Kim","James R Goss","Robert J Allaway"]
          manifestation fundingAgency         studyId
1 ["Hyperexcitability"]      ["NTAP"] ["syn11374345"]
                                                                                                                                                                          studyName
1 ["Leveraging human induced pluripotent stem cells (iPSCs) to determine the impact of patient-derived NF1 gene mutations on peripheral sensory neuron-driven Schwann cell growth"]

> new_pubs <- add_publications_from_file("~/Downloads/Publications-NFOSI-202 - Sheet1.csv", "syn16857542", "syn16787123", dry_run = F) 
Rows: 123 Columns: 1                                                                                                                                                             
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): pmid

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'CsvFileTable' object has no attribute 'pmid'
  ```
  
  What do you think?

2022-06-29 05:44 UTC, allaway commented on R/add_publication_from_pubmed.R
> +        message(glue::glue('PMID:{new_data$pmid} added!'))
I think this is the culprit.

2022-06-29 05:44 UTC, allaway commented on R/add_publication_from_pubmed.R
> +        new_data <- .syn$store(new_data)
```suggestion
        new_data_stored <- .syn$store(new_data)
```

2022-06-29 05:53 UTC, allaway commented on R/add_publication_from_pubmed.R
> +        new_data_stored <- .syn$store(new_data)
```suggestion
        new_data <- .syn$store(new_data)
```

2022-06-29 05:54 UTC, allaway commented on R/add_publication_from_pubmed.R
> +        message(glue::glue('PMID:{new_data$pmid} added!'))
```suggestion
        message(glue::glue('PMID:{new_data$asDataFrame()$pmid} added!'))
```

2022-06-29 05:56 UTC, allaway approved these changes

2022-06-29 05:57 UTC, allaway commented
Turns out it was an easy fix!

2022-06-29 14:44 UTC, anngvu commented
@allaway Awesome, thanks for the fix!

2022-06-29 14:44 UTC, merged