Strandedness test function
nf-osi/nfportalutils pull request #72
Opened 2022-10-11 19:21 UTC by allaway

Created a function to test whether salmon inferred libType is the same as what was provided in the sample sheet. Previous experience indicates that getting this wrong _is a problem_. Ideally, this could be tested pre-workflow, but the cost of setting up an EC2 to do this, installing salmon,  and manually (spot checking or testing all input files)[https://gist.github.com/allaway/d49fbf8faee381ec628032d976b50a38] is probably more complex and costly than just running the workflow and testing post-hoc.

2022-10-11 19:53 UTC, allaway commented
I'm not sure why this is failing...it passes locally.

2022-10-11 20:47 UTC, allaway commented
Figured it out :)

2022-10-14 17:46 UTC, allaway commented
@anngvu conflicts should be resolved now!

2022-10-17 15:07 UTC, anngvu approved these changes
Just one comment, but seems to work well enough. @jaybee84 may have other useful suggestions.

2022-10-17 15:07 UTC, anngvu commented on R/nextflow_testing_utils.R
> +#'  check_libtype_validity(syn_out = 'syn30840584', samplesheet = "syn39593587") #should fail
Couldn't check the fail file example "syn39593587" because of the current permissions (not downloadable), but I think I got a good enough sense with the code test with the real file "syn30841441" above, so will approve.

2022-10-17 19:29 UTC, jaybee84 requested changes
I tested the `check_libtype_validity` function using the following parameters:
```
nfportalutils::check_libtype_validity(syn_out = "syn34572734", samplesheet = "syn34573564")
```
This is a known RNAseq run where the strand check should fail (see multiqc report: syn34573576)

But I get a passed message:
```
nfportalutils::check_libtype_validity(syn_out = "syn34572734", samplesheet = "syn34573564")
Getting file from Synapse...
Going through the outputs...this may take some seconds.
Joining, by = "sample"
💚 Test passed: All samplesheet library type/strandedness match expected values.
            sample   output_id salmon_libtype salmon_libtype_mod strandedness libtype_matches
 1: sampleX syn34574646            ISF            forward      forward            TRUE
 2: sampleY syn34574646            ISF            forward      forward            TRUE
```

2022-10-17 19:59 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +    if("cmd_info.json" %in% unlist(x)) list(sample = x[[1]][[1]],
The `"libType": "ISF"` in the cmd.json(syn34574646) for the test dataset is likely dictated by what is provided by the sample sheet.

2022-10-17 20:00 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +    if("cmd_info.json" %in% unlist(x)) list(sample = x[[1]][[1]],
I recommend using the data in `rseqc_infer_experiment.txt` file for this test

2022-10-17 21:19 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +    if("cmd_info.json" %in% unlist(x)) list(sample = x[[1]][[1]],
This is the relevant file for the test dataset: https://www.synapse.org/#!Synapse:syn34573365

2022-10-17 23:17 UTC, allaway commented on R/nextflow_testing_utils.R
> +    if("cmd_info.json" %in% unlist(x)) list(sample = x[[1]][[1]],
Yeah, looks like you are right, thanks for catching that.

That's a bummer, because Salmon provides more information and theoretically allows us to check more types (https://salmon.readthedocs.io/en/latest/library_type.html) - though in practice, I only see ISR, ISF, IU in NF data, I think. 

I'll poke around a bit to see if there's a log file or anything, as salmon _does_ print the inferred library type at the beginning of each run (though maybe this is only if it is not explicitly declared?). 

I considered using the rseqc_... but I didn't do it because then I have to determine what the cutoffs are to "call" unstranded vs reverse vs forward. I am guessing most data would be ~99 vs ~1%, ~50% vs ~50%, and 1% vs 99%, but I don't really know if that's true, ie. do you sometimes see 25% vs 75% and is that unstranded, or reverse (though perhaps more importantly maybe we should fail that sample...) Do you know if there's any documentation about these ratios for infer_experiment?

2022-10-18 20:17 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +    if("cmd_info.json" %in% unlist(x)) list(sample = x[[1]][[1]],
According to the docs of [infer_experiment.py](https://rseqc.sourceforge.net/#infer-experiment-py), it looks like a formula like `[percent mapped to sense/(100- percent undetermined) ] >  0.5` will be labeled as `sense strand`

Alternatively, multiqc_data.json makes this flag for us. So we could extract this info from that json file. We need to check samples that fall under the following key:
```
report_saved_raw_data": {
        "multiqc_warning:_fail_strand_check": {
            "sample-XYZ": {
                "Provided strandedness": "forward",
                "Inferred strandedness": "reverse",
                "Sense (%)": 1.1800000444054604,
                "Antisense (%)": 89.02999758720398,
                "Undetermined (%)": 9.790000319480896
            },
```
Only samples that fail the strand check will be reported under the key: `multiqc_warning:_fail_strand_check":`

2022-10-18 20:19 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +    if("cmd_info.json" %in% unlist(x)) list(sample = x[[1]][[1]],
If no samples fail the strand check, then this key is not present in the JSON file.

2022-11-09 20:29 UTC, allaway commented on R/nextflow_testing_utils.R
> +    if("cmd_info.json" %in% unlist(x)) list(sample = x[[1]][[1]],
>Alternatively, multiqc_data.json makes this flag for us. So we could extract this info from that json file.

Thanks for doing the 🔬 on this. This looks like it could be a good option.

2022-11-10 02:26 UTC, allaway commented
Alright, this now uses multiqc_data.json. This is a much simpler approach because it actually has the two strandednesses (inferred and provided) available, so the comparison is easier. @jaybee84 could you test and lmk if it works for you?

```
#'  out <- check_libtype_validity(multiqc_id = 'syn29530566') #should pass
#'  out <- check_libtype_validity(multiqc_id = 'syn34573377') #should fail
```

2022-12-07 17:04 UTC, allaway commented
@jaybee84 just a friendly reminder about this review :)

2022-12-07 22:09 UTC, jaybee84 requested changes

2022-12-07 22:09 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +  foo <- jsonlite::fromJSON(jqr::jq(file(jsn), '[. | {warn: .report_saved_raw_data."multiqc_warning:_fail_strand_check"}]'), flatten = F )
Suggest adding a meaningful error message if a wrong file type is provided.

I tested with the synid of a multiqc.html file and the error I get is : 
```
check_libtype_validity(multiqc_id = 'syn34573576')
 >> Error: Invalid numeric literal at line 1, column 10
```

The error is not meaningful to the user but all the function wants to say here is that I was looking for a `json` file and I did not get that.

2022-12-07 22:09 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +check_libtype_validity <- function(multiqc_id){
```suggestion
check_libtype_validity <- function(multiqc_data_json_id){
```

2022-12-07 22:09 UTC, jaybee84 commented on R/nextflow_testing_utils.R
> +check_libtype_validity <- function(multiqc_id){
suggest this var name just to be super explicit..

2022-12-07 22:10 UTC, jaybee84 commented
Tested with an example and the function works very well. Added a couple of small comments to improve user experience :)

2023-11-17 15:17 UTC, allaway commented
Closing because the new RNAseq workflow has strandedness detection built in, which obviates the need for this check.

2023-11-17 15:17 UTC, closed without merging