Feat/nf datasets
nf-osi/nfportalutils pull request #74
Opened 2022-10-20 05:54 UTC by anngvu

2022-10-25 20:16 UTC, allaway requested changes
Haven't tested the functions yet.

2022-10-25 20:16 UTC, allaway commented on R/datasets.R
> +  dataset_items <- lapply(dataset_items, function(entity) list(entityId = entity, versionNumber = 1L))
Curious why this defaults to V1. Alternatively, can we assume the latest version is the "good" version if someone is making a dataset?

2022-10-25 20:16 UTC, allaway commented on R/datasets.R
> +      dataset_items <- lapply(dataset$output_id, function(entity) list(entityId = entity, versionNumber = 1L))
Curious why this defaults to V1. Alternatively, can we assume the latest version is the "good" version if someone is making a dataset?

2022-10-25 20:16 UTC, allaway commented on R/datasets.R
> +  WORKFLOW <- c("FreeBayes", "Mutect2", "Strelka", "DeepVariant")
Should this be a parameter instead?

2023-07-04 00:16 UTC, anngvu commented
@allaway There is one known test failure in https://github.com/nf-osi/nfportalutils/actions/runs/5449425127/jobs/9913626204?pr=74#step:6:1392 (`get_dependency_from_json_schema `) because we updated the data model. It's outside the scope/theme of this PR, so will fix later.

2023-07-10 17:42 UTC, allaway approved these changes
Looks good to me! I have not tested everything, but I have a dataset that I should be processing in the next week or so and will have the opportunity to do then and flag any issues.

2023-07-10 17:42 UTC, allaway commented on R/datasets.R
> +use_latest_in_collection <- function(collection_id, items = "all") {
```suggestion
use_latest_in_collection <- function(collection_id, items = "all") {
```
This is great!!!

2023-07-10 21:17 UTC, merged